### PR TITLE
Write the commit file

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by moozzyk** [comment]
What does this do (or maybe why is it needed)?

**Comment by pranavkm** [comment]
It's writing the commit hash to the artifacts dir. The CI build expects to see the file there

**Comment by pranavkm** [comment]
It's from https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_k-standard-goals.shade#L98, but because you overwrite the target, the file doesn't get written out.

**Comment by moozzyk** [comment]
Isn't it just to add an attribute to the assembly? The thing is that there are no assemblies here so it seems weird and unneeded.

**Comment by pranavkm** [comment]
Well the idea is to be able to tell what set of commits a build came from.

**Comment by muratg** [comment]
:shipit:

**Comment by halter73** [comment]
This isn't part of Universe anymore. No need to merge https://github.com/aspnet/Universe/commit/8667e2496b1441d7f6308fec85af3cf78788954b

**Comment by pranavkm** [comment]
No longer needed

**Pull request closed without merging**
