### PR TITLE
* Converting win versioned RIDs to base win RIDs

### PR DESCRIPTION
**Pull request by moozzyk**
* Removing distro specific Linux RIDs

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]
LGTM

**Comment by moozzyk** [comment]
I'll merge it tomorrow morning to be able to react to build which probably went out of sync since it ran the last time (as it always does)

**Comment by natemcmaster** [comment]
Will this support Windows XP?

jk. :shipit:

**Comment by moozzyk** [comment]
@natemcmaster Win95 and up.

**Pull request merged**
